name = "Chess"
uuid = "717200cc-f167-4fd3-b4bf-b5e480529844"
authors = ["Tord Romstad"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
